Repository cloudquery/cq-provider-k8s, pull requests merged in 2022-01, with the labels that each got.

#41 chore: Synced file(s) with cloudquery/.github
  .github/release.yml
  .github/workflows/add_tags.yml
  .github/workflows/doc_validation.yml
  .github/workflows/golang_lint.yml
  .github/workflows/mock_test.yml
  .github/workflows/pr_title.yml
  .github/workflows/release.yml
  .golangci.yml
Labels: chore

#42 feat: Testable Migrations
  .github/workflows/test_migration.yml
  client/testing.go
  go.mod
  go.sum
  resources/provider/migrations/postgres/1_v0.4.0.down.sql
  resources/provider/migrations/postgres/1_v0.4.0.up.sql
  resources/provider/migrations/timescale/1_v0.4.0.down.sql
  resources/provider/migrations/timescale/1_v0.4.0.up.sql
  resources/provider/provider.go
  resources/provider/provider_test.go
  tools/migrations/main.go
Labels: feat

#43 feat: Upgrade SDK v0.7.0
  go.mod
  go.sum
Labels: feat

#44 chore: Synced file(s) with cloudquery/.github
  .github/workflows/test_migration.yml
Labels: ignore-for-release
