Repository cloudquery/cq-provider-k8s, pull requests merged in 2022-05, with the labels that each got.

#91 fix: Kube context configuration logic fixed
  client/client.go
  docs/index.md
Labels: fix

#85 feat: Add error classifier
  .github/workflows/test_integration.yml.generated-cq-provider-k8s..yml
  .golangci.yaml
  CHANGELOG.md
  client/errors.go
  go.mod
  go.sum
  main.go
  resources/integration_tests/README.md
  resources/provider/provider.go
  resources/services/apps/daemon_sets.go
  resources/services/apps/daemon_sets_mock_test.go
  resources/services/apps/deployments.go
  resources/services/apps/deployments_mock_test.go
  resources/services/apps/replica_sets.go
  resources/services/apps/replica_sets_test.go
  resources/services/apps/stateful_sets.go
  resources/services/apps/stateful_sets_mock_test.go
  resources/services/batch/cron_jobs.go
  resources/services/batch/cron_jobs_mock_test.go
  resources/services/batch/jobs.go
  resources/services/batch/jobs_mock_test.go
  resources/services/core/endpoints.go
  resources/services/core/endpoints_mock_test.go
  resources/services/core/limit_ranges.go
  resources/services/core/limit_ranges_mock_test.go
  resources/services/core/namespaces.go
  resources/services/core/namespaces_mock_test.go
  resources/services/core/nodes.go
  resources/services/core/nodes_mock_test.go
  resources/services/core/pods.go
  resources/services/core/pods_mock_test.go
  resources/services/core/resource_quotas.go
  resources/services/core/resource_quotas_mock_test.go
  resources/services/core/service_accounts.go
  resources/services/core/service_accounts_mock_test.go
  resources/services/core/services.go
  resources/services/networking/network_policies.go
  resources/services/networking/network_policies_mock_test.go
  resources/services/rbac/role_bindings.go
  resources/services/rbac/role_bindings_mock_test.go
  resources/services/rbac/roles.go
  resources/services/rbac/roles_test.go
  resources/services/testing/data.go
Labels: feat

#90 chore(deps): Delete `dependabot.yml`
  .github/dependabot.yml
Labels: ignore-for-release
